import { Header } from '@/components/header'
import { SearchIcon } from '@/components/icons/searchIcon'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Github APi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='d-flex justify-content-center align-items-center mt-10 header-index'>
          <Header></Header>
        </div>
        <div className="row mt-2 d-flex justify-content-center">
          <div className="col-lg-6 d-flex">
            <input className='searchUser' placeholder='Cari Penguna Github' />
            <button className='button ms-2 shadow-sm'> <SearchIcon></SearchIcon> </button>
          </div>
        </div>
      </main>
    </>
  )
}
